/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/theme.ts
 * Command: astryx theme build src/theme/theme.ts --out src/theme/gofer-pixel-theme.css
 * Generated: 2026-08-07T10:33:09.513Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const goferPixelTheme: DefinedTheme;
